//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuStaffWebportal
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", ConfigurationName="CuStaffWebportal.CuStaffWebportal_Port")]
    public interface CuStaffWebportal_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal:FnSavePasswordResetToken" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<CuStaffWebportal.FnSavePasswordResetToken_Result> FnSavePasswordResetTokenAsync(CuStaffWebportal.FnSavePasswordResetToken request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal:FnResetPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<CuStaffWebportal.FnResetPassword_Result> FnResetPasswordAsync(CuStaffWebportal.FnResetPassword request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal:FnChangePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<CuStaffWebportal.FnChangePassword_Result> FnChangePasswordAsync(CuStaffWebportal.FnChangePassword request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal:FnMFALogin", ReplyAction="*")]
        System.Threading.Tasks.Task<CuStaffWebportal.FnMFALogin_Result> FnMFALoginAsync(CuStaffWebportal.FnMFALogin request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal:FnUpdateOTPCode", ReplyAction="*")]
        System.Threading.Tasks.Task<CuStaffWebportal.FnUpdateOTPCode_Result> FnUpdateOTPCodeAsync(CuStaffWebportal.FnUpdateOTPCode request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal:FnSendEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<CuStaffWebportal.FnSendEmail_Result> FnSendEmailAsync(CuStaffWebportal.FnSendEmail request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal:FnLeaveApplication", ReplyAction="*")]
        System.Threading.Tasks.Task<CuStaffWebportal.FnLeaveApplication_Result> FnLeaveApplicationAsync(CuStaffWebportal.FnLeaveApplication request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal:FnCancelDocumentApproval" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<CuStaffWebportal.FnCancelDocumentApproval_Result> FnCancelDocumentApprovalAsync(CuStaffWebportal.FnCancelDocumentApproval request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal:FnGetStaffLeaveBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<CuStaffWebportal.FnGetStaffLeaveBalance_Result> FnGetStaffLeaveBalanceAsync(CuStaffWebportal.FnGetStaffLeaveBalance request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal:FnGetLeaveDates", ReplyAction="*")]
        System.Threading.Tasks.Task<CuStaffWebportal.FnGetLeaveDates_Result> FnGetLeaveDatesAsync(CuStaffWebportal.FnGetLeaveDates request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnSavePasswordResetToken", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", IsWrapped=true)]
    public partial class FnSavePasswordResetToken
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", Order=0)]
        public string jString;
        
        public FnSavePasswordResetToken()
        {
        }
        
        public FnSavePasswordResetToken(string jString)
        {
            this.jString = jString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnSavePasswordResetToken_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", IsWrapped=true)]
    public partial class FnSavePasswordResetToken_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", Order=0)]
        public string return_value;
        
        public FnSavePasswordResetToken_Result()
        {
        }
        
        public FnSavePasswordResetToken_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnResetPassword", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", IsWrapped=true)]
    public partial class FnResetPassword
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", Order=0)]
        public string jString;
        
        public FnResetPassword()
        {
        }
        
        public FnResetPassword(string jString)
        {
            this.jString = jString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnResetPassword_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", IsWrapped=true)]
    public partial class FnResetPassword_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", Order=0)]
        public string return_value;
        
        public FnResetPassword_Result()
        {
        }
        
        public FnResetPassword_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnChangePassword", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", IsWrapped=true)]
    public partial class FnChangePassword
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", Order=0)]
        public string jString;
        
        public FnChangePassword()
        {
        }
        
        public FnChangePassword(string jString)
        {
            this.jString = jString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnChangePassword_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", IsWrapped=true)]
    public partial class FnChangePassword_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", Order=0)]
        public string return_value;
        
        public FnChangePassword_Result()
        {
        }
        
        public FnChangePassword_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnMFALogin", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", IsWrapped=true)]
    public partial class FnMFALogin
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", Order=0)]
        public string jString;
        
        public FnMFALogin()
        {
        }
        
        public FnMFALogin(string jString)
        {
            this.jString = jString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnMFALogin_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", IsWrapped=true)]
    public partial class FnMFALogin_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", Order=0)]
        public string return_value;
        
        public FnMFALogin_Result()
        {
        }
        
        public FnMFALogin_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnUpdateOTPCode", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", IsWrapped=true)]
    public partial class FnUpdateOTPCode
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", Order=0)]
        public string jString;
        
        public FnUpdateOTPCode()
        {
        }
        
        public FnUpdateOTPCode(string jString)
        {
            this.jString = jString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnUpdateOTPCode_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", IsWrapped=true)]
    public partial class FnUpdateOTPCode_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", Order=0)]
        public string return_value;
        
        public FnUpdateOTPCode_Result()
        {
        }
        
        public FnUpdateOTPCode_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnSendEmail", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", IsWrapped=true)]
    public partial class FnSendEmail
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", Order=0)]
        public string subject;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", Order=1)]
        public string recipients;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", Order=2)]
        public string emailMessage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", Order=3)]
        public string ccRecipients;
        
        public FnSendEmail()
        {
        }
        
        public FnSendEmail(string subject, string recipients, string emailMessage, string ccRecipients)
        {
            this.subject = subject;
            this.recipients = recipients;
            this.emailMessage = emailMessage;
            this.ccRecipients = ccRecipients;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnSendEmail_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", IsWrapped=true)]
    public partial class FnSendEmail_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", Order=0)]
        public bool return_value;
        
        public FnSendEmail_Result()
        {
        }
        
        public FnSendEmail_Result(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnLeaveApplication", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", IsWrapped=true)]
    public partial class FnLeaveApplication
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", Order=0)]
        public string jString;
        
        public FnLeaveApplication()
        {
        }
        
        public FnLeaveApplication(string jString)
        {
            this.jString = jString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnLeaveApplication_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", IsWrapped=true)]
    public partial class FnLeaveApplication_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", Order=0)]
        public string return_value;
        
        public FnLeaveApplication_Result()
        {
        }
        
        public FnLeaveApplication_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnCancelDocumentApproval", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", IsWrapped=true)]
    public partial class FnCancelDocumentApproval
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", Order=0)]
        public string jString;
        
        public FnCancelDocumentApproval()
        {
        }
        
        public FnCancelDocumentApproval(string jString)
        {
            this.jString = jString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnCancelDocumentApproval_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", IsWrapped=true)]
    public partial class FnCancelDocumentApproval_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", Order=0)]
        public string return_value;
        
        public FnCancelDocumentApproval_Result()
        {
        }
        
        public FnCancelDocumentApproval_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnGetStaffLeaveBalance", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", IsWrapped=true)]
    public partial class FnGetStaffLeaveBalance
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", Order=0)]
        public string jString;
        
        public FnGetStaffLeaveBalance()
        {
        }
        
        public FnGetStaffLeaveBalance(string jString)
        {
            this.jString = jString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnGetStaffLeaveBalance_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", IsWrapped=true)]
    public partial class FnGetStaffLeaveBalance_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", Order=0)]
        public string return_value;
        
        public FnGetStaffLeaveBalance_Result()
        {
        }
        
        public FnGetStaffLeaveBalance_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnGetLeaveDates", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", IsWrapped=true)]
    public partial class FnGetLeaveDates
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", Order=0)]
        public string jString;
        
        public FnGetLeaveDates()
        {
        }
        
        public FnGetLeaveDates(string jString)
        {
            this.jString = jString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FnGetLeaveDates_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", IsWrapped=true)]
    public partial class FnGetLeaveDates_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CuStaffWebportal", Order=0)]
        public string return_value;
        
        public FnGetLeaveDates_Result()
        {
        }
        
        public FnGetLeaveDates_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface CuStaffWebportal_PortChannel : CuStaffWebportal.CuStaffWebportal_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class CuStaffWebportal_PortClient : System.ServiceModel.ClientBase<CuStaffWebportal.CuStaffWebportal_Port>, CuStaffWebportal.CuStaffWebportal_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CuStaffWebportal_PortClient() : 
                base(CuStaffWebportal_PortClient.GetDefaultBinding(), CuStaffWebportal_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CuStaffWebportal_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CuStaffWebportal_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(CuStaffWebportal_PortClient.GetBindingForEndpoint(endpointConfiguration), CuStaffWebportal_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CuStaffWebportal_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CuStaffWebportal_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CuStaffWebportal_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CuStaffWebportal_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CuStaffWebportal_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CuStaffWebportal.FnSavePasswordResetToken_Result> CuStaffWebportal.CuStaffWebportal_Port.FnSavePasswordResetTokenAsync(CuStaffWebportal.FnSavePasswordResetToken request)
        {
            return base.Channel.FnSavePasswordResetTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<CuStaffWebportal.FnSavePasswordResetToken_Result> FnSavePasswordResetTokenAsync(string jString)
        {
            CuStaffWebportal.FnSavePasswordResetToken inValue = new CuStaffWebportal.FnSavePasswordResetToken();
            inValue.jString = jString;
            return ((CuStaffWebportal.CuStaffWebportal_Port)(this)).FnSavePasswordResetTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CuStaffWebportal.FnResetPassword_Result> CuStaffWebportal.CuStaffWebportal_Port.FnResetPasswordAsync(CuStaffWebportal.FnResetPassword request)
        {
            return base.Channel.FnResetPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<CuStaffWebportal.FnResetPassword_Result> FnResetPasswordAsync(string jString)
        {
            CuStaffWebportal.FnResetPassword inValue = new CuStaffWebportal.FnResetPassword();
            inValue.jString = jString;
            return ((CuStaffWebportal.CuStaffWebportal_Port)(this)).FnResetPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CuStaffWebportal.FnChangePassword_Result> CuStaffWebportal.CuStaffWebportal_Port.FnChangePasswordAsync(CuStaffWebportal.FnChangePassword request)
        {
            return base.Channel.FnChangePasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<CuStaffWebportal.FnChangePassword_Result> FnChangePasswordAsync(string jString)
        {
            CuStaffWebportal.FnChangePassword inValue = new CuStaffWebportal.FnChangePassword();
            inValue.jString = jString;
            return ((CuStaffWebportal.CuStaffWebportal_Port)(this)).FnChangePasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CuStaffWebportal.FnMFALogin_Result> CuStaffWebportal.CuStaffWebportal_Port.FnMFALoginAsync(CuStaffWebportal.FnMFALogin request)
        {
            return base.Channel.FnMFALoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<CuStaffWebportal.FnMFALogin_Result> FnMFALoginAsync(string jString)
        {
            CuStaffWebportal.FnMFALogin inValue = new CuStaffWebportal.FnMFALogin();
            inValue.jString = jString;
            return ((CuStaffWebportal.CuStaffWebportal_Port)(this)).FnMFALoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CuStaffWebportal.FnUpdateOTPCode_Result> CuStaffWebportal.CuStaffWebportal_Port.FnUpdateOTPCodeAsync(CuStaffWebportal.FnUpdateOTPCode request)
        {
            return base.Channel.FnUpdateOTPCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<CuStaffWebportal.FnUpdateOTPCode_Result> FnUpdateOTPCodeAsync(string jString)
        {
            CuStaffWebportal.FnUpdateOTPCode inValue = new CuStaffWebportal.FnUpdateOTPCode();
            inValue.jString = jString;
            return ((CuStaffWebportal.CuStaffWebportal_Port)(this)).FnUpdateOTPCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CuStaffWebportal.FnSendEmail_Result> CuStaffWebportal.CuStaffWebportal_Port.FnSendEmailAsync(CuStaffWebportal.FnSendEmail request)
        {
            return base.Channel.FnSendEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<CuStaffWebportal.FnSendEmail_Result> FnSendEmailAsync(string subject, string recipients, string emailMessage, string ccRecipients)
        {
            CuStaffWebportal.FnSendEmail inValue = new CuStaffWebportal.FnSendEmail();
            inValue.subject = subject;
            inValue.recipients = recipients;
            inValue.emailMessage = emailMessage;
            inValue.ccRecipients = ccRecipients;
            return ((CuStaffWebportal.CuStaffWebportal_Port)(this)).FnSendEmailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CuStaffWebportal.FnLeaveApplication_Result> CuStaffWebportal.CuStaffWebportal_Port.FnLeaveApplicationAsync(CuStaffWebportal.FnLeaveApplication request)
        {
            return base.Channel.FnLeaveApplicationAsync(request);
        }
        
        public System.Threading.Tasks.Task<CuStaffWebportal.FnLeaveApplication_Result> FnLeaveApplicationAsync(string jString)
        {
            CuStaffWebportal.FnLeaveApplication inValue = new CuStaffWebportal.FnLeaveApplication();
            inValue.jString = jString;
            return ((CuStaffWebportal.CuStaffWebportal_Port)(this)).FnLeaveApplicationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CuStaffWebportal.FnCancelDocumentApproval_Result> CuStaffWebportal.CuStaffWebportal_Port.FnCancelDocumentApprovalAsync(CuStaffWebportal.FnCancelDocumentApproval request)
        {
            return base.Channel.FnCancelDocumentApprovalAsync(request);
        }
        
        public System.Threading.Tasks.Task<CuStaffWebportal.FnCancelDocumentApproval_Result> FnCancelDocumentApprovalAsync(string jString)
        {
            CuStaffWebportal.FnCancelDocumentApproval inValue = new CuStaffWebportal.FnCancelDocumentApproval();
            inValue.jString = jString;
            return ((CuStaffWebportal.CuStaffWebportal_Port)(this)).FnCancelDocumentApprovalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CuStaffWebportal.FnGetStaffLeaveBalance_Result> CuStaffWebportal.CuStaffWebportal_Port.FnGetStaffLeaveBalanceAsync(CuStaffWebportal.FnGetStaffLeaveBalance request)
        {
            return base.Channel.FnGetStaffLeaveBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<CuStaffWebportal.FnGetStaffLeaveBalance_Result> FnGetStaffLeaveBalanceAsync(string jString)
        {
            CuStaffWebportal.FnGetStaffLeaveBalance inValue = new CuStaffWebportal.FnGetStaffLeaveBalance();
            inValue.jString = jString;
            return ((CuStaffWebportal.CuStaffWebportal_Port)(this)).FnGetStaffLeaveBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CuStaffWebportal.FnGetLeaveDates_Result> CuStaffWebportal.CuStaffWebportal_Port.FnGetLeaveDatesAsync(CuStaffWebportal.FnGetLeaveDates request)
        {
            return base.Channel.FnGetLeaveDatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CuStaffWebportal.FnGetLeaveDates_Result> FnGetLeaveDatesAsync(string jString)
        {
            CuStaffWebportal.FnGetLeaveDates inValue = new CuStaffWebportal.FnGetLeaveDates();
            inValue.jString = jString;
            return ((CuStaffWebportal.CuStaffWebportal_Port)(this)).FnGetLeaveDatesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CuStaffWebportal_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CuStaffWebportal_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://desktop-p80si0s.redcross.or.ke:6022/Kapsowar-Live/WS/AIC Kapsowar Mission " +
                        "Hospital/Codeunit/CuStaffWebportal");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CuStaffWebportal_PortClient.GetBindingForEndpoint(EndpointConfiguration.CuStaffWebportal_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CuStaffWebportal_PortClient.GetEndpointAddress(EndpointConfiguration.CuStaffWebportal_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            CuStaffWebportal_Port,
        }
    }
}
